### ISSUE TITLE
ServiceNotFoundException in Symfony 4

### ISSUE THREAD

**Issue by vzenix** [neo4j-contrib/neo4j-symfony#49]
ServiceNotFoundException

The "neo4j.client" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead.

My composer.json is it:

```
{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "friendsofsymfony/rest-bundle": "^2.3",
        "graphaware/neo4j-common": "^3.5",
        "graphaware/neo4j-php-ogm": "^1.0@RC",
        "jms/serializer-bundle": "^2.4",
        "neo4j/neo4j-bundle": "^0.4.1",
        "sensio/framework-extra-bundle": "^5.1",
        "symfony/console": "^4.1",
        "symfony/flex": "^1.0",
        "symfony/framework-bundle": "^4.1",
        "symfony/lts": "^4@dev",
        "symfony/yaml": "^4.1"
    },
    "require-dev": {
        "symfony/dotenv": "^4.1"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false
        }
    }
}
```

And my code is it:

```
<?php
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use FOS\RestBundle\Controller\Annotations as FOSRest;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\JsonResponse;

/**
 * @Route("/api/v1")
 */
class DemoController extends Controller
{

    /**
     * Test
     * @FOSRest\Get("/test")
     * @return array
     */
    public function test()
    {
        $client = $this->getNeo4jClient();
        $results = $client->run('MATCH (n:Movie) RETURN n LIMIT 5');
        $element = array();
        foreach ($results->records() as $record) {
            $node = $record->get('n');
            $element[] = $node->get('title'); // "The Matrix"
        }

        $iResponse = new JsonResponse();
        $iResponse->setData(array('demo' => true, 'elements' => $element));
        return $iResponse;
    }

    /**
     * @return \GraphAware\Neo4j\Client\Client
     */
    private function getNeo4jClient()
    {
        return $this->get('neo4j.client');
    }
}
```

**Comment by vzenix** [comment]
At the end i solve it apply decorators to the services for do the connection, i put the example if someone have the same problem.

Add to [root symfony]/config/services.yaml

```
    Neo4j\Neo4jBundle\Factory\ClientFactory:
        alias: neo4j.factory.client
        public: true

    neo4j.connection.custom:
        decorates: neo4j.connection.default
        class: GraphAware\Neo4j\Client\Connection\Connection
        public: true
        arguments: 
            - 'default'
            - '%env(NEO4J_CONNECTION)%'

    neo4j.client.custom:
        decorates: neo4j.client
        class: GraphAware\Neo4j\Client\Client
        public: true
        # pass the old service as an argument
        arguments: ['@neo4j.connection_manager']
```

Add to [root symfony]/.env and [root symfony]/.env.dist

`NEO4J_CONNECTION="http://<username>:<password>@localhost:7474"`


Then you need use the new service for clients

```
    /**
     * @return \GraphAware\Neo4j\Client\Client
     */
    private function getNeo4jClient()
    {
        return $this->container->get('neo4j.client.custom');
    }
```
